### ISSUE TITLE
very slow read

### ISSUE THREAD

**Issue by dodler** [zarr-developers/zarr-python#647] opened 2020-11-06 21:07 UTC
Hi, zarr read become very slow (drop from 30 minutes to 9 hours) after i start reading (not zarr) files in another program from another disk. 

it actually looks like this.
![image](https://user-images.githubusercontent.com/6881262/98414816-1f261880-208d-11eb-996b-2c81b23e6a95.png)

i'm using zarr 2.5.0

**Comment by rabernat** [comment] 2020-11-19 04:47
Hi @dodler. Thanks for reporting your problem. I'm not sure this is an issue with Zarr, since it depends on your personal computer, details of your dataset, your operating system, as well as other programs you happen to be running. It's impossible to conclude much based on this very short description you provided, so I'm going to close this issue.

If you are still convinced you have discovered a performance regression with Zarr, please feel free to reopen this issue with a [minimum reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) which will allow the Zarr developers to investigate your issue.

**Closed by rabernat** 2020-11-19 04:47 UTC
