### ISSUE TITLE
zarr slower than npy, hdf5 etc?

### ISSUE THREAD

**Issue by nschloe** [zarr-developers/zarr-python#519] opened 2019-11-19 21:48 UTC
I got interested in the performance of zarr and did a comparison with npy, pickle, hdf5 etc. See https://stackoverflow.com/a/58942584/353337. To my surprise, I found zarr reads large arrays slower than npy. This is for random float data as well as more structured mesh data. I had expected zarr to take the cake using multiple cores. Perhaps this isn't a good test for zarr to show its strength either.

![out](https://user-images.githubusercontent.com/181628/130753238-462b3749-dbc4-4fc8-a605-a4e027ad1fbf.png)

Code to reproduce the plot:

```python
import perfplot
import pickle
import numpy
import h5py
import tables
import zarr


def setup(n):
    data = numpy.random.rand(n)
    # import meshzoo
    # n = int(numpy.cbrt(n))
    # points, cells = meshzoo.cube(
    #    xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=0.0, zmax=1.0, nx=n, ny=n, nz=n
    # )
    # data = cells
    # write all files
    #
    numpy.save("out.npy", data)
    #
    f = h5py.File("out.h5", "w")
    f.create_dataset("data", data=data)
    f.close()
    #
    with open("test.pkl", "wb") as f:
        pickle.dump(data, f)
    #
    f = tables.open_file("pytables.h5", mode="w")
    gcolumns = f.create_group(f.root, "columns", "data")
    f.create_array(gcolumns, "data", data, "data")
    f.close()
    #
    zarr.save("out.zip", data)
    zarr.save("out.zarr", data)


def npy_read(data):
    return numpy.load("out.npy")


def hdf5_read(data):
    f = h5py.File("out.h5", "r")
    out = f["data"][()]
    f.close()
    return out


def pickle_read(data):
    with open("test.pkl", "rb") as f:
        out = pickle.load(f)
    return out


def pytables_read(data):
    f = tables.open_file("pytables.h5", mode="r")
    out = f.root.columns.data[()]
    f.close()
    return out


def zarr_zarr_read(data):
    return zarr.load("out.zarr")


def zarr_zip_read(data):
    return zarr.load("out.zip")


b = perfplot.bench(
    setup=setup,
    kernels=[
        npy_read,
        hdf5_read,
        pickle_read,
        pytables_read,
        zarr_zarr_read,
        zarr_zip_read,
    ],
    n_range=[2 ** k for k in range(23)],
    xlabel="len(data)",
)
b.save("out.png")
b.show()
```

**Comment by alimanfoo** [comment] 2019-11-19 22:05
Thanks for posting, interesting. Couple of factors may be at work here.

In the read test you use zarr in a zip file. IIUC reading from zip adds
some overhead because the CRCs are checked. I'd suggest comparing with zarr
stored as files in a directory (as you do for the write test).

Also when comparing zarr versus h5, if you wanted to be totally fair you'd
need to use the same chunk sizes and the same compressor. In your benchmark
you don't explicitly set the chunk size, so zarr and h5py will guess a
chunk size from the data size, and both use the same algorithm for guessing
chunk size but zarr is tuned to guess larger chunks. This may not make a
difference in your benchmark but thought I'd mention. Also you don't
explicitly set the compressor, and h5py and zarr have different defaults.
Again may not make a difference here, but worth noting.

**Comment by nschloe** [comment] 2019-11-19 22:39
I've updated the original post to include zipped zarr vs directory zarr; same results.

I suppose it must be the default for the compressor then.

**Comment by vigji** [comment] 2019-11-22 09:48
I am doing a similar testing and I was trying to understand whether in zarr it is possible to read partially the file to get only some slices of the array. If I compare performance on partial retrieval with hdf5 files, where I know this is possible, I get a much longer time to read small chunks of the data (smaller than the zarr chunk size), and this seem to come from the fact that zarr reads the entire chunk to return part of it. Is there any way to get a partial file reading in zarr?

**Comment by jakirkham** [comment] 2019-11-22 14:45
@nschloe, are these using the same compressor and chunk size? It seems like they may not be, which could cause huge variability.

**Comment by nschloe** [comment] 2019-11-22 14:52
@jakirkham I don't know; I just used the default values. See the code for how to reproduce the plot.

**Comment by constantinpape** [comment] 2019-11-22 15:51
>  I don't know; I just used the default values.

Afaik, zarr uses blosc compression by default. h5py does not compress by default.
Also, h5py does not chunk the data if you don't specify `chunks=True` (or enable compression).
Numpy and pickle neither compress nor chunk, I don't know about pytables.
So the comparison is not very fair.

FWIW when I benchmarked z5, which implements the zarr spec bin C++, I found the performance
on par with hdf5 in single-threaded performance and better mult-threaded. Unfortunately I don't have the results right now, [the code is here](https://github.com/constantinpape/z5/tree/master/src/bench).

**Comment by nschloe** [comment] 2019-11-23 12:46
Can I adjust chunking and compression in `zarr.save`?

**Comment by constantinpape** [comment] 2019-11-23 15:05
> Can I adjust chunking and compression in `zarr.save`?

You will need to use `zarr.save_array` instead and call it like this:
```
zarr.save_array('out.zr', data, chunks=chunks, compressor=compressor)
```
Chunks needs to  be a tuple with the chunk size you want. Compressor can either be `None` (= no compression) or one of the compressors from `numcodecs`.

> Can I enable multithreading in Python?

As far as I am aware there is no convenience function to read/write multi-threaded in `zarr-python` and you will need to implement this yourself. (I might be wrong about this though, `zarr-python` has grown quite a bit since I looked at it in detail for the last time ....)

**Comment by rabernat** [comment] 2019-11-23 15:34
To get multithreading in python, use zarr together with dask. That’s the recommended way to go.

**Comment by nschloe** [comment] 2019-11-24 18:29
> use zarr together with dask

I see. I suppose you're using dask arrays then, which is perhaps easy to do since they support memory segmentation with their blocked arrays.

In my opinion, it's still worthwhile exploring the possibility of using multithreaded reads into numpy arrays. Those  are the de-facto standard, every Python programmer knows them and lots of code is optimized for it. It should be possible, too: You know in advance how large the block in memory will be, and where each chunk will go.

**Comment by rabernat** [comment] 2019-11-24 19:13
If you don’t mind the dask dependency, it would be simple to just use dask for the reading step. If you call dask.array.from_zarr and then coerce immediately to a numpy array, you will effectively get what you’re looking for.

**Comment by jakirkham** [comment] 2019-11-24 19:19
Would add I’m not aware of NumPy or pickle doing multithreaded reads or writes. Though am not sure if we are still discussing benchmarking.

**Comment by nschloe** [comment] 2019-11-24 19:52
> Would add I’m not aware of NumPy or pickle doing multithreaded reads or writes. Though am not sure if we are still discussing benchmarking.

They don't and yes. I _want_ to see zarr benchmarks which show file sizes smaller than pickle/npy (they already are) and (almost) equally fast reads (not possible without multithreading it seems).

**Comment by jakirkham** [comment] 2019-11-24 20:15
Well they are also writing a single file. I suppose one could have a Zarr file with a single chunk.

Anyways I think before we jump to conclusions we need a good benchmark. The first pass gave us a starting point albeit there are issues with it as pointed out. Can we do a second pass that integrates this feedback?

**Comment by nschloe** [comment] 2019-12-05 13:33
Okay, well compression _does_ make a difference after all, at least with file sizes. In particular with structured data, zarr is way ahead of the competition. The compression also explains the slower read times.

![filesizes-random-float](https://user-images.githubusercontent.com/181628/70239566-d0307e80-176b-11ea-9ac3-d718b040e2a8.png) |
![filesizes-random-int](https://user-images.githubusercontent.com/181628/70239567-d0307e80-176b-11ea-98d6-27b6877e23a1.png)
|:---:|:------:|
![filesizes-structured-float](https://user-images.githubusercontent.com/181628/70239569-d0c91500-176b-11ea-8828-293b28357f68.png) | ![filesizes-structured-int](https://user-images.githubusercontent.com/181628/70239570-d0c91500-176b-11ea-99b5-f6f29135b44c.png)

In particular with structured data, zarr is way ahead of the competition.

```python
def check_file_sizes():
    file_sizes = []
    n_range = [2 ** k for k in range(23)]
    for n in n_range:
        setup_random_int(n)
        # setup_random_float(n)
        # setup_structured_float(n)
        # setup_structured_int(n)
        file_sizes.append([
            os.stat("out.npy").st_size,
            os.stat("out.h5").st_size,
            os.stat("out.pkl").st_size,
            os.stat("pytables.h5").st_size,
            os.stat("out.zip").st_size,
            sum(f.stat().st_size for f in Path('out.zarr').glob('**/*') if f.is_file()),
        ])

    labels = ["npy", "h5", "pickle", "pytables", "zarr zip", "zarr dir"]

    file_sizes = numpy.array(file_sizes).T

    # sort by last entry
    idx = numpy.argsort(file_sizes[:, -1])[::-1]
    file_sizes = [file_sizes[i] for i in idx]
    labels = [labels[i] for i in idx]

    for fs, label in zip(file_sizes, labels):
        plt.loglog(n_range, fs, label=label)

    plt.legend()
    plt.xlabel("n")
    plt.title("file sizes (random int)")
    plt.ylabel("filesize [B]")
    plt.grid()
    # plt.show()
    plt.savefig("filesizes-random-int.png", transparent=True, bbox_inches="tight")
```

**Comment by nschloe** [comment] 2019-12-05 13:45
Well, how do I set the compressor? This
```
      from numcodecs import Blosc  
      compressor = Blosc(cname="zlib", clevel=4)  
      zarr.save("out.zip", data, compressor=compressor)
```
gives the cryptic
```
ValueError: missing object_codec for object array
```

**Comment by jakirkham** [comment] 2019-12-05 15:34
What is `data`?

**Comment by nschloe** [comment] 2019-12-05 15:39
A numpy array. (Edited the above code.)

**Comment by vedal** [comment] 2022-11-14 17:18
@rabernat 
> To get multithreading in python, use zarr together with dask. That’s the recommended way to go.

Is this still the recommendation? Maybe this issue is mature for closing?

**Comment by joshmoore** [comment] 2022-11-14 19:16
@vedal: wow. Yes. This is mature for closing, indeed! Nevertheless, for multithreading, etc. zarr-python :heart: dask.

**Closed by joshmoore** 2022-11-14 19:16 UTC

**Comment by joshmoore** [comment] 2022-11-15 11:36
> I suppose by zarr-python you mean instead of xarray

Yes, exactly.

> Do you happen to know of a piece of modern example code or other source for how to combine them efficiently?

The [dask.array.from_zarr](https://docs.dask.org/en/stable/generated/dask.array.from_zarr.html) and [dask.array.to_zarr](https://docs.dask.org/en/stable/generated/dask.array.to_zarr.html) methods are likely what you are looking for.

> I couldnt find much about Dask in zarr-pythons [official docs](https://zarr.readthedocs.io/en/stable/tutorial.html)

This is a good point. At the moment, Zarr is "low-level" and so doesn't try to explain how to use the other tools with it. But links from the documentation would definitely be useful. Sorry about that! We'll look into it.

**Comment by vedal** [comment] 2022-11-15 13:07
@joshmoore thanks alot for these clarifications and for being concrete! I'm surprised that zarr+dask would be alot better since xarray also seems to use dask.DataArray under-the-hood.

**Comment by joshmoore** [comment] 2022-11-15 15:16
> I noticed there is an open issue on zarr+dask as well, so it made me unsure of the maturity of the duo: [#962](https://github.com/zarr-developers/zarr-python/issues/962)

I'll update the description of this issue. Here the problem is that someone tried to wrap a dask in a zarr, but you should put a zarr in your dask. :smile:
