### ISSUE TITLE
docs: weird version number in browser tab

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#2012] opened 2024-07-04 14:14 UTC
### Zarr version

current

### Numcodecs version

N/A

### Python Version

N/A

### Operating System

N/A

### Installation

N/A

### Description

![image](https://github.com/zarr-developers/zarr-python/assets/88113/663e28af-c7fd-4654-b066-63b64bab62cb)

Version number listed is oddly 0.1.dev50 on https://zarr.readthedocs.io/en/stable/

### Steps to reproduce

Visit https://zarr.readthedocs.io/en/stable/

**Comment by dstansby** [comment] 2024-07-07 15:55
This is a duplicate of https://github.com/zarr-developers/zarr-python/issues/2016 (or vice versa)

**Comment by MSanKeys963** [comment] 2024-07-17 00:20
The latest build of RTD looks fine. Check: https://zarr.readthedocs.io/en/latest/.
Fixes were added in #1985 and #1987. A new alpha release may solve this.

**Comment by joshmoore** [comment] 2024-07-17 06:32
Not sure that's the case, @MSanKeys963. stable is built from the main branch, i.e. from the last non-alpha tag. A non-pre-release tag, i.e. the release of v3 will do it based on `/latest/` but the 2.x line looks to be broken.

**Comment by dstansby** [comment] 2024-07-17 08:03
Might be https://github.com/pypa/setuptools_scm/issues/84 that this is running into

**Comment by dstansby** [comment] 2024-08-28 07:51
I think this is fixed by https://github.com/zarr-developers/zarr-python/pull/2044

**Closed by dstansby** 2024-08-28 07:51 UTC
Labels: bug
