### ISSUE TITLE
Azure (`adlfs`) stores raise `KeyError` when chunk is all fill value (chunk file doesn't exist)

### ISSUE THREAD

**Issue by tasansal** [zarr-developers/zarr-python#1150] opened 2022-09-28 18:22 UTC
### Zarr version

v2.13.2

### Numcodecs version

v0.10.2

### Python Version

3.10

### Operating System

Linux/Windows

### Installation

using pip into virtual environment

### Description

When using `zarr` and `adlfs`, while reading, the missing chunks (fill value filled) raise a key error.

This doesn't happen in Google Cloud or AWS using `gcsfs` or `s3fs`.

### Steps to reproduce

```python
azure_auth = {
    "account_name": "mystorageaccount",
    "account_key": "my-secret-key",
}

adl_store = zarr.storage.FSStore("az://container/my.zarr", mode="w", **azure_auth)

adl_array = adl_root.create_dataset(
    name="my_array",
    shape=(5, 5),
    chunks=(1, 1),
)

adl_array[2, 2] = 1  # __setitem__ works ok

adl_array[:]  # read whole array
```
The `KeyError` gets raised at the final read. Traceback in Additional Output section.

### Additional output

---------------------------------------------------------------------------

```python
KeyError                                  Traceback (most recent call last)
Cell In [5], line 1
----> 1 adl_array[:]

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/zarr/core.py:807, in Array.__getitem__(self, selection)
    805     result = self.vindex[selection]
    806 else:
--> 807     result = self.get_basic_selection(pure_selection, fields=fields)
    808 return result

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/zarr/core.py:933, in Array.get_basic_selection(self, selection, out, fields)
    930     return self._get_basic_selection_zd(selection=selection, out=out,
    931                                         fields=fields)
    932 else:
--> 933     return self._get_basic_selection_nd(selection=selection, out=out,
    934                                         fields=fields)

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/zarr/core.py:976, in Array._get_basic_selection_nd(self, selection, out, fields)
    970 def _get_basic_selection_nd(self, selection, out=None, fields=None):
    971     # implementation of basic selection for array with at least one dimension
    972 
    973     # setup indexer
    974     indexer = BasicIndexer(selection, self)
--> 976     return self._get_selection(indexer=indexer, out=out, fields=fields)

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/zarr/core.py:1272, in Array._get_selection(self, indexer, out, fields)
   1269 else:
   1270     # allow storage to get multiple items at once
   1271     lchunk_coords, lchunk_selection, lout_selection = zip(*indexer)
-> 1272     self._chunk_getitems(lchunk_coords, lchunk_selection, out, lout_selection,
   1273                          drop_axes=indexer.drop_axes, fields=fields)
   1275 if out.shape:
   1276     return out

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/zarr/core.py:2012, in Array._chunk_getitems(self, lchunk_coords, lchunk_selection, out, lout_selection, drop_axes, fields)
   2010 else:
   2011     partial_read_decode = False
-> 2012     cdatas = self.chunk_store.getitems(ckeys, on_error="omit")
   2013 for ckey, chunk_select, out_select in zip(ckeys, lchunk_selection, lout_selection):
   2014     if ckey in cdatas:

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/zarr/storage.py:1368, in FSStore.getitems(self, keys, **kwargs)
   1366 def getitems(self, keys, **kwargs):
   1367     keys_transformed = [self._normalize_key(key) for key in keys]
-> 1368     results = self.map.getitems(keys_transformed, on_error="omit")
   1369     # The function calling this method may not recognize the transformed keys
   1370     # So we send the values returned by self.map.getitems back into the original key space.
   1371     return {keys[keys_transformed.index(rk)]: rv for rk, rv in results.items()}

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/fsspec/mapping.py:101, in FSMap.getitems(self, keys, on_error)
     96     raise KeyError from e
     97 out = {
     98     k: (KeyError() if isinstance(v, self.missing_exceptions) else v)
     99     for k, v in out.items()
    100 }
--> 101 return {
    102     key: out[k2]
    103     for key, k2 in zip(keys, keys2)
    104     if on_error == "return" or not isinstance(out[k2], BaseException)
    105 }

File /home/username/miniconda3/envs/my_env/lib/python3.10/site-packages/fsspec/mapping.py:104, in <dictcomp>(.0)
     96     raise KeyError from e
     97 out = {
     98     k: (KeyError() if isinstance(v, self.missing_exceptions) else v)
     99     for k, v in out.items()
    100 }
    101 return {
    102     key: out[k2]
    103     for key, k2 in zip(keys, keys2)
--> 104     if on_error == "return" or not isinstance(out[k2], BaseException)
    105 }

KeyError: 'container/my.zarr/my_array/0.0'
```

**Comment by ErlendHaa** [comment] 2022-09-28 19:37
Hi,

The root cause lies in adlfs, this patch addresses it https://github.com/fsspec/adlfs/pull/350

**Comment by tasansal** [comment] 2022-09-28 20:34
Should we close this then, or leave it to be tested when `adlfs` fix is released? @zarrdevelopers

**Comment by jakirkham** [comment] 2022-09-29 02:24
cc @martindurant (for awareness)

**Comment by jakirkham** [comment] 2022-09-29 15:24
Thanks Martin! Do you also have thoughts on PR ( https://github.com/fsspec/adlfs/pull/350 )?

**Comment by martindurant** [comment] 2022-09-29 15:53
I can see it's a little painful, but I think adlfs supporting on_error is probably a good things. We can consider separately whether fsspec's invocation should be robust to missing keys.

**Comment by dstansby** [comment] 2024-07-15 06:42
I think this can be closed now as fixed in `adlfs`?

**Closed** 2024-07-16 17:21 UTC
Labels: bug
