### ISSUE TITLE
Zarr not cleaning up after MetadataError

### ISSUE THREAD

**Issue by ivirshup** [zarr-developers/zarr-python#490] opened 2019-10-23 08:21 UTC
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
import zarr

z = zarr.open("tmp.zarr")
z.create_dataset(
    "throws_error",
    data=["a", "b", "c"],
    dtype=[("a", object), ("b", object)]
)  # Throws an error
assert "throws_error" in z  # The key is set
z["throws_error"]  # Access throws an error
```

#### Problem description

For certain failures to write an array, zarr isn't cleaning up after itself. I expected that there wouldn't be an entry for the key if setting the value failed.

#### Version and installation information

*  `zarr v2.3.2`
* `numcodecs v0.6.3`
* `python v3.7.4`
* On a mac
* With pip installed zarr and numcodecs

**Comment by jhamman** [comment] 2024-10-17 23:03
I'm unable to reproduce this in 3.0.0.beta. Closing.

**Closed by jhamman** 2024-10-17 23:03 UTC
