### ISSUE TITLE
Memory leak when saving in parallel

### ISSUE THREAD

**Issue by alejoe91** [zarr-developers/zarr-python#1129] opened 2022-09-09 08:23 UTC
### Zarr version

v2.12.0

### Numcodecs version

v0.10.2

### Python Version

3.9.13

### Operating System

Linux

### Installation

using pip (in a conda environment)

### Description

Hi Zarr team!

We use the `ProcessPoolExecutor` to distribute writing to different Zarr chunks over different jobs (see [here](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/job_tools.py#L298-L301))

The [function](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/core_tools.py#L693-L709) that each job runs simply loads a buffer and saves it to the appropriate zarr array location. 
We noticed, that the buffer that is saved to zarr ([traces](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/core_tools.py#L704-L705)) is not properly garbage collected  and this makes the RAM usage grow as the process continues. 
We patched it on our side by forcing a garbace collection [in-place](https://github.com/SpikeInterface/spikeinterface/pull/915).

We think this issue is related to Zarr because we have the exact same mecanism to [write to binary files](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/core_tools.py#L206-L218) and in that case the RAM usage is what we expect.

### Steps to reproduce

The problem can be reproduced using SpikeInterface v0.94.0:

```
>>> pip install spikeinterface[full]==0.94.0
```

Here is a sample script to reproduce the issue:
```
import spikeinterface.full as si

# generate a sample recording
recording, _ = si.toy_example(num_channels=64, duration=600, num_segments=1)

# save it to zarr with parallization (by default it will use blosc-zstd)
recording_zarr = recording.save(format="zarr", zarr_path="test_ram.zarr", n_jobs=4, total_memory="500M",
                                                     progress_bar=True)
```

Note that the chunk size is adjusted so that the number of jobs times the memory needed by each chunk is ~500MB (`total_memory`).

**Comment by joshmoore** [comment] 2022-09-09 08:40
Thanks for the write up, @alejoe91. I don't see anything immediately surprising in https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/core_tools.py#L635-L709 which definitely makes me worry. Could you help us understand what zarr-level calls are being made in a typical run?

**Comment by alejoe91** [comment] 2022-09-09 09:46
@joshmoore sure, here is how the zarr calls are distributed:

1. The `save()` function is routed to this [`_save()`](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/baserecording.py#L245-L299) function which is specific to Zarr. Here the zarr file is created and several groups and small datasets are added  to it.
2. The [`write_traces_to_zarr`](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/baserecording.py#L273) does the actual writing. 
   * we create the [large datasets](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/core_tools.py#L635-L644) making sure that the chunk size matches the chunk sizes that the parallel processing uses (so we write to non-overlapping blocks)
   * the parallel processing is carried out by the `ChunkRecordingExecutor` class, which internally uses the built-in [ProcessPoolExecutor](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/job_tools.py#L298-L315)
   * each job is initialized with an [`_init_func`](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/core_tools.py#L660-L690), which allows us to do operations that are only required once (e.g., we reopen the [Zarr object](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/core_tools.py#L681) and store the datasets that needs writing in a `context`)
   * the [_write_zarr_chunk](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/core_tools.py#L694-L709) is then run for each chunk: it [retrieves the data that need to be written](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/core_tools.py#L702-L704) and writes them to the [zarr dataset](https://github.com/SpikeInterface/spikeinterface/blob/37538ab0cca595a9a1a93806471b0667e7b6e25a/spikeinterface/core/core_tools.py#L705)

I hope this makes it clearer!

**Comment by alejoe91** [comment] 2022-09-22 16:39
Hi @joshmoore 

Sorry for the delay in getting back to you. 

I tested on my local machine and it seems that RAM usage is under control and it doesn't grow as reported here. 

I initially encountered the issue using a cloud resource from GCP, so that might be the issue. 
I'll repeat the test there to see if that architecture is triggering the abnormal RAM consumption.

Here is a log which prints the start_frame, end_frame, and RAM usage at each iteration (using 4 jobs, 1s chunk size). I'll provide the same log when running on GCP in a few days.

[zarr_garbage_log.txt](https://github.com/zarr-developers/zarr-python/files/9627750/zarr_garbage_log.txt)

**Comment by johnurbanik** [comment] 2022-12-01 20:25
@alejoe91 when you encountered the initial issue, were you storing the Zarr on GCS?

If so, I think I'm running into the same thing... In my case, data I've written to a Zarr group that uses gcsfs isn't garbage collected.

**Comment by dstansby** [comment] 2024-10-19 19:17
Since this issue is quite old now, and it needs more info to debug or progress, I'm going to close it. Thanks all for taking the time to open or contribute - if this is still an issue, please leave a comment (ideally with a more specific and simple example, with code to reproduce) and I can re-open this.

**Closed by dstansby** 2024-10-19 19:17 UTC
Labels: bug
