### ISSUE TITLE
Conversion from .h5 file to zarr using copy_all when .h5 file consists of objects of type bytes

### ISSUE THREAD

**Issue by prkprime** [zarr-developers/zarr-python#576] opened 2020-07-22 10:58 UTC
I'm posting the [StackOverflow link](https://stackoverflow.com/questions/63031802/im-getting-a-typeerror-when-converting-h5-hdf5-file-into-zarr-format) in which the h5 to zarr conversion is failing because of the following error
```bash
TypeError: Object of type bytes is not JSON serializable
```
So is there any implementation that can solve this problem?

**Comment by joshmoore** [comment] 2020-07-22 11:17
Hi @prkprime. You might give https://github.com/catalystneuro/HDF5Zarr a try.

**Comment by dstansby** [comment] 2024-12-28 10:00
Thanks for reporting the issue - since there isn't a small self contained example we can use to reproduce the issue, and this has been open for a while, I'm going to close this because there's not much action we can take. Feel free to open a new issue though if you're still having issues!

**Closed by dstansby** 2024-12-28 10:00 UTC
